apiVersion: v1
kind: Service
metadata:
  name: heartbeat
spec:
  selector:
    app: heartbeat
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat
spec:
  replicas: 10
  selector:
    matchLabels:
      app: heartbeat
  template:
    metadata:
      labels:
        app: heartbeat
    spec:
      containers:
      - name: heartbeat
        image: {your-registry}.azurecr.io/heartbeatapi:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
